# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: My New Future
email: zach.dyer@zachdyerdesign.com
description: New Future ministry website
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mynewfuture.net" # the base hostname & protocol for your site
banner: boysunset.jpg

# Build settings
markdown: kramdown

gems:
  - jekyll-sitemap
